---
- name: Wipe previous runs
  when: web_app_full_wipe | bool
  block:
    - name: Get running containers
      docker_host_info:
        containers: yes
        images: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Remove images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_info.images | map(attribute='Id') | list }}"

    - name: Remove previous configuration
      ansible.builtin.file:
        path: /etc/docker-compose.yml
        state: absent
  tags: ['wipe']

- name: Deploy docker
  block:
  - name: Template a docker-compose.yml to /etc/
    ansible.builtin.template:
      src: "docker-compose.yml.j2"
      dest: /etc/docker-compose.yml
      mode: '0644'

  - name: Create and start web service
    community.docker.docker_compose:
      project_src: /etc/
      pull: true
  tags: ['web_app']