apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
spec:
  selector:
    matchLabels:
      app: app-python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: ilyakolomin/devops_app_python:latest
        ports:
        - containerPort: 8000
          name: app-python-svc