global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'app_python'
    static_configs:
      - targets: ['app_python:8000']
  - job_name: 'app_go'
    static_configs:
      - targets: ['app_go:8080']
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']