apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  editable: true
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true